-- Drop tables
DROP TABLE episodeIV;

-- Activity 2:
-- Creating the table
CREATE TABLE episodeIV (name STRING, line STRING) 
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t' TBLPROPERTIES ("skip.header.line.count"="2");

-- Load file into the table
LOAD DATA LOCAL INPATH '/root/inputs/episodeIV_dialogues.txt' INTO TABLE episodesIV;

-- Generate output and export it
INSERT OVERWRITE LOCAL DIRECTORY '/root/HiveProjectOutput2'
SELECT COUNT(*) FROM episodeIV WHERE line LIKE '%Luke%';
