services:
    redis-server:
        image: 'redis'
        volumes:
            - ./redis:/data
        command: ["redis-server", "--protected-mode", "no", "--save", "1 1"]
    node-app:
        build: ./
        image: docker.io/dimplebadiye/visits
        ports:
            - "8081:8081"